name: Gradle Build and Test

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Run unit tests
        run: ./gradlew test

#name: Gradle Build and Test: Назва вашого робочого процесу.
#
#on: pull_request: Ця подія запускає робочий процес, коли відкривається Pull Request.
#
#branches: - main: Обмежує запуск тільки для Pull Request, що направлені в гілку main.
#
#runs-on: ubuntu-latest: Виконує завдання на віртуальній машині з Ubuntu.
#
#actions/setup-java@v4: Цей крок встановлює Java Development Kit (JDK),
  #що є необхідним для запуску Gradle. Версія 17 є однією з найпопулярніших LTS версій.
  #Ви можете змінити її, якщо ваш проєкт потребує іншої.
#
#chmod +x gradlew: Ця команда надає файлу gradlew права на виконання,
  #що є обов'язковим кроком для запуску сценаріїв Gradle на Linux-подібних системах.
#
#./gradlew test: Ця команда запускає юніт-тести, визначені у вашому проєкті.
  #Це стандартна команда для запуску тестів у Gradle.